name: Continuous Delivery

on:
  push:
    branches: [main]

permissions:
  contents: write   # create tag & release
  id-token: write   # OIDC for PyPI if using trusted-publisher

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Install semantic-release
        run: pip install python-semantic-release
      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: semantic-release publish  # = version + build + changelog + tag + upload
