name: Continuous Delivery
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write        # commit + tag + release notes
  id-token: write        # OIDC for PyPI

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    # -- pull full history so previous tags are visible --
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }

    - uses: actions/setup-python@v5
      with: { python-version: '3.11' }

    # 1️⃣ bump version, commit, tag, create GH release
    - name: Python Semantic Release
      id: semrel
      uses: python-semantic-release/python-semantic-release@v9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # 2️⃣ build your dists only if a release happened
    - name: Build dists
      if: steps.semrel.outputs.released == 'true'
      run: |
        pip install build
        python -m build

    # 3️⃣ upload to PyPI (trusted-publisher via OIDC)
    - name: Publish to PyPI
      if: steps.semrel.outputs.released == 'true'
      uses: pypa/gh-action-pypi-publish@v1.8.11
      with:
        skip_existing: true

    # 4️⃣ upload artefacts to the GitHub Release
    - name: Attach dists to Release
      if: steps.semrel.outputs.released == 'true'
      uses: python-semantic-release/publish-action@v9   # ← new action
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.semrel.outputs.tag }}
        directory: dist
